### ISSUE TITLE
kerasff - Evaluation error: missing value where TRUE/FALSE needed.

### ISSUE THREAD

**Issue by JackyP** [mlr-org/mlr3keras#18]
The following minimal example leads to an error:

```{r}
iris_task <- tsk("iris")  
lrn_keras_ff <- lrn("classif.kerasff")
lrn_keras_ff$train(iris_task)
```

The error is:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: missing value where TRUE/FALSE needed.

Detailed traceback: 
  File "/Users/Jacky/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/Jacky/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 372, in fit
    prefix='val_')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/Jacky/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 685, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/Jacky/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 298, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Library/Frameworks/R.fra
```

The tests currently include the line:
```
po_lrn$param_set$values$layer_units = integer()
```
This suppresses the error, consequently tests pass, but it looks like something doesn't work. I'm not sure what's causing this.

**Comment by pfistfl** [comment]
The code you posted above runs fine for me. 

One reason for the code not working for you might be keras / tensorflow version. 
I had some trouble getting it to work with tensorflow versions >= 2.0.1

Hence I added 
> mlr3keras is currently tested and works using the python packages keras (2.3.1) and tensorflow (2.0.0).

to the `README` for now.

**Comment by JackyP** [comment]
I double checked the python keras and tensorflow by rerunning

```
keras::install_keras(version="2.3.1", tensorflow="2.0.0", extra_packages = c("tensorflow-hub", "tabnet==0.1.4.1"))
```

However the problem persists for me. What version of the r packages for keras and tensorflow are you using? Both the latest github versions keras: ``e3f62ae2`` and tensorflow: ``f2ba22df`` and CRAN versions ``keras_2.2.5.0``, ``tensorflow_2.0.0`` do not work for me either.

**Comment by pfistfl** [comment]
So a colleague seemed to have the same problem. 
I do not really understand how this problem came up.

My versions:
```
> [1] reticulate_1.13.0-9004 tensorflow_2.0.0       keras_2.2.5.0  
```

You can do 
```r
library(reticulate)
tf = import("tensorflow")
tf$`__version__`
```

to see whether the installation part of your above script worked.
(Maybe `reticulate` uses some other python path?)

**Comment by pfistfl** [comment]
I will close this now, as this does not seem to persist. I would hope that this is just an error stemming from a missmatch between R's `keras` version and the installed `keras`'s version.

Please reopen if this still persists.

**Comment by JackyP** [comment]
N.b. this was due to ``verbose`` not being defaulted to any value and being left as null at the time. It should no longer be an issue with later versions.
