### ISSUE TITLE
AttributeError: 'Adam' object has no attribute '.__enclos_env__'

### ISSUE THREAD

**Issue by AtharKharal** [mlr-org/mlr3keras#29]
While using mlr3verse 3.6.3 and tensorflow 2.0 the creation of learner as:
lrn('classif.tabnet')
 produces following error:
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'Adam' object has no attribute '.__enclos_env__'

Any help please?

**Comment by pfistfl** [comment]
Hey, thanks for the report.

Can you try to install the latest `paradox` using

`remotes::install_github("mlr-org/paradox")`

and see if that works?

**Comment by AtharKharal** [comment]
Thanks indeed, it is working now.
