### ISSUE TITLE
mlr3keras Installation Error

### ISSUE THREAD

**Issue by drag05** [mlr-org/mlr3keras#31]
I am trying to install `mlr3keras` on R v. 4.0.2 and get the following error:

```
 remotes::install_github('mlr-org/mlr3keras')

Downloading GitHub repo mlr-org/mlr3keras@master

Error: Failed to install 'mlr3keras' from GitHub:
  Missing commas separating Remotes: 'mlr-org/bbotk
    mlr-org/mlr3'
```
Please advise. Thank you!

**Comment by pfistfl** [comment]
fixed, perhaps try again. Thanks for reporting

**Comment by drag05** [comment]
@pfistfl 

Installation worked, thank you!

**Comment by pfistfl** [comment]
Please note, that mlr3keras is currently under development and might have minor bugs @drag05 
Feel free to report anything!

**Comment by drag05** [comment]
@pfistfl 

Hello Florian,
Thank you, I will! 

I have just run github 'iris' example and it worked smoothly with conda `tensorflow-gpu 2.1.0`, `cudatoolkit 10.1.243` 
 and `cudnn 7.6.5`
