### ISSUE TITLE
Feature request: Regression

### ISSUE THREAD

**Issue by JackyP** [mlr-org/mlr3keras#5]
Currently there is only classification. It would be nice to have the equivalent of LearnerClassifKeras for Regr. 

A cool feature to have would be a y_range for regression of non-negative (apply exponential at the last layer) or range-bound (apply sigmoid transform) similar to how the fast.ai tabular does it.

Would be interested to help.

**Comment by pfistfl** [comment]
Hey, absolutely!
- This is on the list, feel free to create a PR with some initial specs!
- Transform: Yes, I think this will be absolutely required.

I would like to find a general design pattern that allows us to have as little duplicate code as possible.
(i.e lots of code can be shared between regr / classif and keras / kerasff).

Any ideas?

**Comment by pfistfl** [comment]
Mostly covered in #8 still missing sigmoid transforms.

**Comment by pfistfl** [comment]
Will close here, Target transforms will come from `mlr3pipelines` hopefully soon(ish).
